/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import control.CFPJuego;
import javax.swing.JOptionPane;
import oovv.Joc;
import oovv.Jugador;
import oovv.Maex;
import oovv.Tutil;

/**
 *
 * @author migue
 */
public class Incio extends javax.swing.JFrame {

    /**
     * Creates new form Incio
     */
    public Incio() {
        initComponents();
        setLocationRelativeTo(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        Personalizar = new javax.swing.JMenuItem();
        Jugar = new javax.swing.JMenuItem();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        Personalizar.setText("Quiero personalizar la ventana");
        Personalizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PersonalizarActionPerformed(evt);
            }
        });
        jPopupMenu1.add(Personalizar);

        Jugar.setText("Quiero empezar a Jugar");
        Jugar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JugarActionPerformed(evt);
            }
        });
        jPopupMenu1.add(Jugar);

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI Semibold", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("¡Bienvenido!");

        jButton1.setText("¿Deseas Jugar?");
        jButton1.setComponentPopupMenu(jPopupMenu1);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addGap(0, 18, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
/**
     * Inicia el Juego cuando pulsamos el boton
     *
     * @param evt al darle al boton
     */
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String nom = JOptionPane.showInputDialog("entra el nom del primer jugador");

        Jugador j1 = null;
        try {
            j1 = new Jugador(nom, Tutil.getAleatori(1000, 9999));
        } catch (Maex maex) {
            try {
                j1 = new Jugador("Pere", Tutil.getAleatori(1000, 9999));
            } catch (Maex ex) {
            }
        }
        nom = JOptionPane.showInputDialog("entra el nom del primer jugador");

        Jugador j2 = null;
        try {
            j2 = new Jugador(nom, Tutil.getAleatori(1000, 9999));
        } catch (Maex ex) {
            try {
                j2 = new Jugador("Andrea", Tutil.getAleatori(1000, 9999));
            } catch (Maex ex1) {
            }
        }
        Joc joc = new Joc(j1, j2);

        FPJuego f = new FPJuego();
        CFPJuego c = new CFPJuego(f, joc);
        f.setOidor(c);
        f.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed
    /**
     * Crea un mensaje cuando se va a cerrar la ventana
     *
     * @param evt al darle a la x de la ventana
     */
    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        int option = JOptionPane.showConfirmDialog(this,
                "¿Estás seguro de que quieres cerrar la aplicación?",
                "Confirmación de cierre",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE);
        if (option == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_formWindowClosing
    /**
     * Inicia la visualizacion FPersonalizar
     *
     * @param evt al hacer click derecho en el boton y darle a quiero
     * personalizar
     */
    private void PersonalizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PersonalizarActionPerformed
        // TODO add your handling code here:
        FPersonalizar fpers = new FPersonalizar();
        fpers.setVisible(true);
    }//GEN-LAST:event_PersonalizarActionPerformed
    /**
     * Inicia el Juego
     *
     * @param evt al hacer click derecho en el boton y darle a quiero jugar
     */
    private void JugarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JugarActionPerformed
        // TODO add your handling code here:
        String nom = JOptionPane.showInputDialog("entra el nom del primer jugador");

        Jugador j1 = null;
        try {
            j1 = new Jugador(nom, Tutil.getAleatori(1000, 9999));
        } catch (Maex maex) {
            try {
                j1 = new Jugador("Pere", Tutil.getAleatori(1000, 9999));
            } catch (Maex ex) {
            }
        }
        nom = JOptionPane.showInputDialog("entra el nom del primer jugador");

        Jugador j2 = null;
        try {
            j2 = new Jugador(nom, Tutil.getAleatori(1000, 9999));
        } catch (Maex ex) {
            try {
                j2 = new Jugador("Andrea", Tutil.getAleatori(1000, 9999));
            } catch (Maex ex1) {
            }
        }
        Joc joc = new Joc(j1, j2);

        FPJuego f = new FPJuego();
        CFPJuego c = new CFPJuego(f, joc);
        f.setOidor(c);
        f.setVisible(true);
        dispose();
    }//GEN-LAST:event_JugarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Incio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Incio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Incio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Incio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Incio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Jugar;
    private javax.swing.JMenuItem Personalizar;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPopupMenu jPopupMenu1;
    // End of variables declaration//GEN-END:variables
}
